modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL="https://github.com/Exploding-Creeper/Hyper-Lighting/issues"

[[mods]]
modId = "hyperlighting"
version = "${modver}"
displayName = "Hyper Lighting"
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/Exploding-Creeper/Hyper-Lighting/"
logoFile="logo.png"
#credits=""
authors="HypherionSA, Misha"
description = '''
Hyper Lighting is an advanced Lighting mod for Minecraft featuring lights of all shapes and colors!
'''

[[dependencies.hyperlighting]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hyperlighting]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"
